<a href="https://colab.research.google.com/github/VenkateshSoni/Word-Embedding/blob/main/Word_Embedding_Techniques_using_Embedding_Layer_in_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Word Embedding Techniques using Embedding Layer in Keras

In [2]:
#Libraries used in Tensorflow > 2.0 and Keras

In [3]:
#if not tensorflow>2.0
from keras.preprocessing.text import one_hot

In [4]:
#in tensorflow > 2.0 you get keras integrated in the tensorflow itself
#for tensorflow > 2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
#sentences
sent = ['the glass of milk',
       'the glass of juice',
       'the cup of tea',
       'I am a good boy',
       'I am a good developer',
       'understand the meaning of words',
       'english is easy', 
       'mathematics is easy',
       'geography is difficult']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'english is easy',
 'mathematics is easy',
 'geography is difficult']

In [7]:
voc_size = 10000 #Size of Dictionary/Vocabulary

In [8]:
#One Hot Representation

In [9]:
onehot_representation = [one_hot(words, voc_size) for words in sent]
print(onehot_representation)
#note that same word indexes are same

[[6477, 3805, 3598, 8148], [6477, 3805, 3598, 7935], [6477, 3275, 3598, 7166], [7538, 4396, 1254, 7086, 433], [7538, 4396, 1254, 7086, 2731], [6213, 6477, 2454, 3598, 2818], [7914, 6491, 7792], [1596, 6491, 7792], [3568, 6491, 7038]]


In [ ]:
#Word Embedding Representation

In [11]:
from tensorflow.keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences 
#from tensorflow.keras.preprocessing.squence import pad_sequences --Not Working*
from tensorflow.keras.models import Sequential #using sequential model inorder to use Embedding Layer

In [12]:
import numpy as np

In [13]:
sent_length = 8
embedded_docs= pad_sequences(onehot_representation, padding = 'pre', maxlen = sent_length)
#pad_sequence = takes in onehot representation, padding 'pre' - adds zeros infornt and make sentences complete
#padding 'post' - adds zeros behind and make sentences complete
print(embedded_docs)

[[   0    0    0    0 6477 3805 3598 8148]
 [   0    0    0    0 6477 3805 3598 7935]
 [   0    0    0    0 6477 3275 3598 7166]
 [   0    0    0 7538 4396 1254 7086  433]
 [   0    0    0 7538 4396 1254 7086 2731]
 [   0    0    0 6213 6477 2454 3598 2818]
 [   0    0    0    0    0 7914 6491 7792]
 [   0    0    0    0    0 1596 6491 7792]
 [   0    0    0    0    0 3568 6491 7038]]


In [14]:
dimension = 10

In [15]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length)) #Embedding Layer - Helps to convert based on number of dimention to featurized representation
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [17]:
print(model.predict(embedded_docs))

[[[-9.44010168e-03 -2.77414173e-03 -2.65349150e-02 -5.63115999e-03
   -4.80329879e-02 -1.41212121e-02 -4.40488830e-02 -2.31506228e-02
   -3.38186510e-02 -2.09537745e-02]
  [-9.44010168e-03 -2.77414173e-03 -2.65349150e-02 -5.63115999e-03
   -4.80329879e-02 -1.41212121e-02 -4.40488830e-02 -2.31506228e-02
   -3.38186510e-02 -2.09537745e-02]
  [-9.44010168e-03 -2.77414173e-03 -2.65349150e-02 -5.63115999e-03
   -4.80329879e-02 -1.41212121e-02 -4.40488830e-02 -2.31506228e-02
   -3.38186510e-02 -2.09537745e-02]
  [-9.44010168e-03 -2.77414173e-03 -2.65349150e-02 -5.63115999e-03
   -4.80329879e-02 -1.41212121e-02 -4.40488830e-02 -2.31506228e-02
   -3.38186510e-02 -2.09537745e-02]
  [-3.53236571e-02  2.42906697e-02 -5.92286512e-03 -7.29446486e-03
    8.10994953e-03 -3.02613378e-02 -1.52160041e-02  5.45822084e-04
    3.29815187e-02  4.28444780e-02]
  [ 1.70703419e-02  2.56060474e-02 -4.00736928e-02  1.96008198e-02
   -1.76679604e-02 -7.39338249e-03  1.64301321e-03 -2.76766308e-02
    3.77671756e-